# Generated by Django 2.0.9 on 2018-10-22 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nobinobi_staff', '0002_auto_20181019_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='birthday_date',
        ),
        migrations.AddField(
            model_name='staff',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth Date'),
        ),
        migrations.AddField(
            model_name='staff',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nobinobi_staff.Team', verbose_name='Team'),
        ),
    ]
