# Generated by Django 2.0.9 on 2018-10-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobinobi_staff', '0003_auto_20181022_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='order',
            field=models.PositiveIntegerField(default=1, unique=True, verbose_name='Order'),
            preserve_default=False,
        ),
    ]
