# Generated by Django 2.0.9 on 2018-11-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobinobi_staff', '0004_team_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absenceattachment',
            options={'verbose_name': 'Absence attachment', 'verbose_name_plural': 'Absence attachments'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AddField(
            model_name='absencetype',
            name='abbr',
            field=models.CharField(default='000', max_length=3, verbose_name='Abbreviation'),
        ),
    ]
