# Generated by Django 2.0.13 on 2020-08-05 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import nobinobi_staff.models


class Migration(migrations.Migration):

    dependencies = [
        ('nobinobi_staff', '0008_add_partial_disability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='abs_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='nobinobi_staff.AbsenceType', verbose_name="Absence Type"),
        ),
    ]
