repos:
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.4  # add version here
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: [ "--without-hashes", "-f", "requirements.txt", "-o", "requirements.txt",]
        verbose: true
      - id: poetry-install
